/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import com.mysql.jdbc.Connection;
import java.sql.SQLException;
import java.awt.Graphics;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.print.*;
import java.awt.print.PrinterException;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author aldot
 */
public class buktiAnak extends javax.swing.JFrame {

    /**
     * Creates new form buktiAnak
     */
    private void printRecord(JPanel panel){
        PrinterJob pj = PrinterJob.getPrinterJob();
        
        pj.setJobName("Print Record");
        
      
        
    }
    
    private void showdata(){
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("umur");
        model.addColumn("tgl");
        model.addColumn("biaya");
        model.addColumn("jadwal");
        model.addColumn("jam");
        
        try{
            int nomer = 1;
            String sql = "SELECT * FROM `daftar anak`";
            java.sql.Connection conn = (Connection)KonfiqAnak.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
            model.addRow(new Object[]{nomer++,res.getString(1),res.getString(2),
                res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            table.setModel(model);
    
    
    
        }catch(SQLException e){
            System.out.println("Error : "+ e.getMessage());
        }
    
    
    }
    
    
    
    public buktiAnak() {
        initComponents();
        showdata();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfpreview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bpri = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txarea = new javax.swing.JTextArea();
        bdelete = new javax.swing.JButton();
        bekluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("JEBAR JEBUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfpreview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfpreview.setText("Preview");
        tfpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpreviewActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        bpri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bpri.setText("Print");
        bpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpriActionPerformed(evt);
            }
        });

        txarea.setBackground(new java.awt.Color(204, 204, 204));
        txarea.setColumns(20);
        txarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txarea.setRows(5);
        jScrollPane3.setViewportView(txarea);

        bdelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        bekluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bekluar.setText("Keluar");
        bekluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bekluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bekluar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfpreview, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bpri, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfpreview)
                        .addGap(18, 18, 18)
                        .addComponent(bdelete)
                        .addGap(9, 9, 9)
                        .addComponent(bekluar)
                        .addGap(147, 147, 147)
                        .addComponent(bpri)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        
        int i  = table.getSelectedRow();
        TableModel model = table.getModel();
        String nama = model.getValueAt(i, 0).toString();
        String umur = model.getValueAt(i, 1).toString();
        String tgl = model.getValueAt(i, 2).toString();
        String biaya = model.getValueAt(i, 3).toString();
        String jadwal = model.getValueAt(i,4).toString();
        String jam = model.getValueAt(i, 5).toString();
    }//GEN-LAST:event_tableMouseClicked

    private void tfpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpreviewActionPerformed
        // TODO add your handling code here:
        
        
        int i  = table.getSelectedRow();
        TableModel model = table.getModel();
        String nama = model.getValueAt(i, 1).toString();
        String umur = model.getValueAt(i, 2).toString();
        
        Date ys = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        String tgl = a.format(ys);
        
                
                
                
        String biaya = model.getValueAt(i, 4).toString();
        String jadwal = model.getValueAt(i,5).toString();
        String jam = model.getValueAt(i, 6).toString();
        
        
        
       txarea.append("============ BUKTI DAFTAR ============ \n\n"
               + "Selamat kamu telah terdaftar di les renang jebar Jebur\n"
               + "dengan identitas :\n"
               + "nama : "+nama+"\n"
               + "Umur : "+umur+"\n"
               + "Biaya : "+biaya+"\n"
               + "Kartu ini dicek saat Kamu memasuki wilayah Kolam Renang Jebar Jebur\n"
               + "Dengan ini Anda Resmi menjadi Keluarga Jebar-Jebur\n"
               + "                                       tgl "+tgl+"\n"
               + "    Masa Berlaku sampai Bulan Berikutnya\n"
               + "============ JEBAR JEBUR ============");
       
        
        
        
        
        
        
    }//GEN-LAST:event_tfpreviewActionPerformed

    private void bpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpriActionPerformed
        try {
            txarea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(buktiAnak.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_bpriActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        
        txarea.setText(" ");
        
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bekluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bekluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bekluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buktiAnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buktiAnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buktiAnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buktiAnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buktiAnak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bekluar;
    private javax.swing.JButton bpri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table;
    private javax.swing.JButton tfpreview;
    private javax.swing.JTextArea txarea;
    // End of variables declaration//GEN-END:variables
}
