/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;


import com.mysql.jdbc.Connection;
import java.sql.SQLException;
import java.awt.Graphics;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.print.*;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author aldot
 */
public class buktiRemaja extends javax.swing.JFrame {

    
    
    
    
    private void showdata(){
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("umur");
        model.addColumn("tgl");
        model.addColumn("biaya");
        model.addColumn("jadwal");
        model.addColumn("jam");
        
        try{
            int nomer = 1;
            String sql = "SELECT * FROM `muridremaja`";
            java.sql.Connection conn = (Connection)KonfiqAnak.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
            model.addRow(new Object[]{nomer++,res.getString(1),res.getString(2),
                res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tableremaja.setModel(model);
    
    
    
        }catch(SQLException e){
            System.out.println("Error : "+ e.getMessage());
        }
    
    
    }
    /**
     * 
     * 
     * 
     * 
     * Creates new form buktiRemaja
     */
    public buktiRemaja() {
        initComponents();
        showdata();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableremaja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpri = new javax.swing.JTextArea();
        bpre = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bekluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("JEBAR JEBUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tableremaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableremaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableremajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableremaja);

        txpri.setColumns(20);
        txpri.setRows(5);
        jScrollPane2.setViewportView(txpri);

        bpre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bpre.setText("Preview");
        bpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpreActionPerformed(evt);
            }
        });

        bprint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bprint.setText("Print");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bekluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bekluar.setText("Keluar");
        bekluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bekluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bpre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bekluar)
                                    .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bpre)
                        .addGap(7, 7, 7)
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)
                        .addComponent(bekluar)
                        .addGap(131, 131, 131)
                        .addComponent(bprint)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableremajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableremajaMouseClicked
        // TODO add your handling code here:
        
         int i  = tableremaja.getSelectedRow();
        TableModel model = tableremaja.getModel();
        String nama = model.getValueAt(i, 0).toString();
        String umur = model.getValueAt(i, 1).toString();
        String tgl = model.getValueAt(i, 2).toString();
        String biaya = model.getValueAt(i, 3).toString();
        String jadwal = model.getValueAt(i,4).toString();
        String jam = model.getValueAt(i, 5).toString();
        
    }//GEN-LAST:event_tableremajaMouseClicked

    private void bpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpreActionPerformed
        // TODO add your handling code here:
        
        int i  = tableremaja.getSelectedRow();
        TableModel model = tableremaja.getModel();
        String nama = model.getValueAt(i, 1).toString();
        String umur = model.getValueAt(i, 2).toString();
        
        Date ys = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        String tgl = a.format(ys);
        
        
                
        String biaya = model.getValueAt(i, 4).toString();
        String jadwal = model.getValueAt(i,5).toString();
        String jam = model.getValueAt(i, 6).toString();
        
        txpri.append("============ BUKTI DAFTAR ============ \n\n"
               + "Selamat kamu telah terdaftar di les renang jebar Jebur\n"
               + "dengan identitas :\n"
               + "nama : "+nama+"\n"
               + "Umur : "+umur+"\n"
               + "Biaya : "+biaya+"\n"
               + "Kartu ini dicek saat Kamu memasuki wilayah Kolam Renang Jebar Jebur\n"
               + "Dengan ini Anda Resmi menjadi Keluarga Jebar-Jebur\n"
               + "                                       tgl "+tgl+"\n"
               + "    Masa Berlaku sampai Bulan Berikutnya\n"
               + "============ JEBAR JEBUR ============");
        
    }//GEN-LAST:event_bpreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txpri.setText(" ");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bekluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bekluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bekluarActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        // TODO add your handling code here:
        
        try {
            txpri.print();
        } catch (PrinterException ex) {
            Logger.getLogger(buktiAnak.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buktiRemaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buktiRemaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buktiRemaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buktiRemaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buktiRemaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bekluar;
    private javax.swing.JButton bpre;
    private javax.swing.JButton bprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableremaja;
    private javax.swing.JTextArea txpri;
    // End of variables declaration//GEN-END:variables
}
