/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;



import com.mysql.jdbc.Connection;
import java.sql.SQLException;
import java.awt.Graphics;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.print.*;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author aldot
 */
public class buktiDewasa extends javax.swing.JFrame {
    

    private void showdata(){
    
    DefaultTableModel mode = new DefaultTableModel();
    mode.addColumn("No");
    mode.addColumn("Nama");
    mode.addColumn("Umur");
    mode.addColumn("Tgl");
    mode.addColumn("Biaya");
    mode.addColumn("Jadwal");
    mode.addColumn("Jam");
    
    
    try{
            int nomer = 1;
            String sql = "SELECT * FROM `murid dewasa`";
            java.sql.Connection conn = (Connection)KonfiqAnak.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
            mode.addRow(new Object[]{nomer++,res.getString(1),res.getString(2),
                res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tabledewasa.setModel(mode);
    
    
    
        }catch(SQLException e){
            System.out.println("Error : "+ e.getMessage());
        }
    
    
    
    }


    
    /**
     * Creates new form buktiiDewasa
     */
    public buktiDewasa() {
        initComponents();
        showdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledewasa = new javax.swing.JTable();
        bpreview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txarea = new javax.swing.JTextArea();
        bprint = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("JEBAR JEBUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabledewasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledewasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledewasaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledewasa);

        bpreview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bpreview.setText("Preview");
        bpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpreviewActionPerformed(evt);
            }
        });

        txarea.setColumns(20);
        txarea.setRows(5);
        jScrollPane2.setViewportView(txarea);

        bprint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bprint.setText("Print");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bhapus.setText("Delete");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bkembali.setText("Keluar");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpreview, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bpreview)
                        .addGap(7, 7, 7)
                        .addComponent(bhapus)
                        .addGap(7, 7, 7)
                        .addComponent(bkembali)
                        .addGap(59, 59, 59)
                        .addComponent(bprint)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabledewasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledewasaMouseClicked
        // TODO add your handling code here:
        int i  = tabledewasa.getSelectedRow();
        TableModel model = tabledewasa.getModel();
        String nama = model.getValueAt(i, 0).toString();
        String umur = model.getValueAt(i, 1).toString();
        
        
        Date ys = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        String tgl = a.format(ys);
        
        
        
        String biaya = model.getValueAt(i, 3).toString();
        String jadwal = model.getValueAt(i,4).toString();
        String jam = model.getValueAt(i, 5).toString();
        
    }//GEN-LAST:event_tabledewasaMouseClicked

    private void bpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpreviewActionPerformed
        // TODO add your handling code here:
        
        int i  = tabledewasa.getSelectedRow();
        TableModel model = tabledewasa.getModel();
        String nama = model.getValueAt(i, 1).toString();
        String umur = model.getValueAt(i, 2).toString();
        String tgl = model.getValueAt(i, 3).toString();
        String biaya = model.getValueAt(i, 4).toString();
        String jadwal = model.getValueAt(i,5).toString();
        String jam = model.getValueAt(i, 6).toString();
        
        txarea.append("============ BUKTI DAFTAR ============ \n\n"
               + "Selamat kamu telah terdaftar di les renang jebar Jebur\n"
               + "dengan identitas :\n"
               + "nama : "+nama+"\n"
               + "Umur : "+umur+"\n"
               + "Biaya : "+biaya+"\n"
               + "Kartu ini dicek saat Kamu memasuki wilayah Kolam Renang Jebar Jebur\n"
               + "Dengan ini Anda Resmi menjadi Keluarga Jebar-Jebur\n"
               + "                                       tgl "+tgl+"\n"
               + "    Masa Berlaku sampai Bulan Berikutnya\n"
               + "============ JEBAR JEBUR ============");
        
        
    }//GEN-LAST:event_bpreviewActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        txarea.setText(" ");
        
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_bkembaliActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        // TODO add your handling code here:
        
        try {
            txarea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(buktiAnak.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buktiDewasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buktiDewasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buktiDewasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buktiDewasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buktiDewasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bpreview;
    private javax.swing.JButton bprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabledewasa;
    private javax.swing.JTextArea txarea;
    // End of variables declaration//GEN-END:variables
}
